title: 'milojevic-dupont.github.io'
description: "PhD candidate, MCC Berlin & TU Berlin"
url: "https://milojevicdupontnikola.github.io"


header_pages:
  - index.md
  - research.md
  - projects.md
  - publications.md
 

style: dark

footer: 'last updated: <span id="demo"><script> var d = new Date(); document.getElementById("demo").innerHTML = d.toDateString();</script></span> - <a href="https://github.com/b2a3e8/jekyll-theme-console">theme</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console


