title: 'milojevic-dupont.github.io'
description: "bla"
baseurl: "/index"
url: "https://milojevicdupontnikola.github.io"


header_pages:
  - index.md
  - cv.md
  - links.md
  - contact.md

style: dark

footer: 'last updated: 11.28.2020'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
