title: 'milojevic-dupont.github.io'
description: "PhD candidate, MCC Berlin & TU Berlin"
url: "https://milojevicdupontnikola.github.io"


header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md

style: dark

footer: 'last updated: 01.21.2021 - <a href="https://github.com/b2a3e8/jekyll-theme-console">theme</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
