title: 'milojevic-dupont.github.io'
description: "PhD candidate, MCC Berlin & TU Berlin"
url: "https://milojevicdupontnikola.github.io"


header_pages:
  - index.md
  - research.md
  - projects.md
  - publications.md
 

style: dark

footer: 'Last updated: 9.12.21 - <a href="https://github.com/b2a3e8/jekyll-theme-console">theme</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console


